export function dashboardHtml(nonce: string): string {
	if (!/^[A-Za-z0-9_-]{16,128}$/.test(nonce)) throw new Error("Invalid dashboard nonce");
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Codetonomy Runs</title>
<style nonce="${nonce}">
:root{color-scheme:dark;--bg:#09131d;--panel:#101f2c;--line:#294258;--text:#e9f3f8;--muted:#91a9b9;--ice:#8bd7f5;--ok:#77d6a1;--bad:#ff8d91}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top left,#17364b 0,var(--bg) 42%);color:var(--text);font:15px/1.45 ui-monospace,SFMono-Regular,Menlo,monospace}header,main{max-width:1180px;margin:auto;padding:24px}header{display:flex;gap:18px;align-items:center}.bear{font-size:42px}.eyebrow{color:var(--ice);font-weight:700;letter-spacing:.08em;text-transform:uppercase}h1,h2{margin:.1em 0}.muted{color:var(--muted)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px}.card,.panel{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:14px;box-shadow:0 14px 40px #0005}.card{padding:16px}.value{font-size:25px;font-weight:750;margin-top:5px}.layout{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(320px,.75fr);gap:16px;margin-top:16px}.panel{overflow:hidden}.panel h2{font-size:16px;padding:16px;border-bottom:1px solid var(--line)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px 14px;border-bottom:1px solid #20374a}th{color:var(--muted);font-size:12px;text-transform:uppercase}button{all:unset;cursor:pointer;color:var(--ice);text-decoration:underline;text-underline-offset:3px}button:focus-visible{outline:2px solid var(--ice);outline-offset:3px}.pill{border-radius:99px;padding:3px 8px;font-size:12px;background:#20384a}.pass{color:var(--ok)}.fail{color:var(--bad)}#details{padding:16px;max-height:68vh;overflow:auto}.metric-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.metric{background:#0c1924;border-radius:8px;padding:10px}.event{padding:9px 0;border-bottom:1px solid #20374a}.event small{display:block;color:var(--muted)}.error{color:var(--bad);padding:16px}@media(max-width:850px){.layout{grid-template-columns:1fr}header,main{padding:16px}th:nth-child(4),td:nth-child(4){display:none}}
</style>
</head>
<body><header><div class="bear" aria-hidden="true">🐻‍❄️</div><div><div class="eyebrow">Codetonomy</div><h1>Verified run observatory</h1><div class="muted">Canonical local traces, costs, tools, and verifier outcomes.</div></div></header>
<main><section id="summary" class="cards" aria-label="Run summary"></section><div class="layout"><section class="panel"><h2>Recent runs</h2><div id="runs"><p class="muted" style="padding:16px">Loading…</p></div></section><aside class="panel"><h2>Run details</h2><div id="details"><p class="muted">Select a run.</p></div></aside></div><section class="panel" style="margin-top:16px"><h2>Benchmark comparisons</h2><div id="benchmarks"><p class="muted" style="padding:16px">No benchmark results yet.</p></div></section><div id="error" role="alert"></div></main>
<script nonce="${nonce}">
const q=new URLSearchParams(location.search),fromUrl=q.get('token');if(fromUrl){sessionStorage.setItem('codetonomy-token',fromUrl);history.replaceState({},'',location.pathname)}const token=sessionStorage.getItem('codetonomy-token')||'';
const api=async path=>{const response=await fetch(path,{headers:{authorization:'Bearer '+token},cache:'no-store'});if(!response.ok)throw new Error((await response.json().catch(()=>({error:response.statusText}))).error||response.statusText);return response.json()};
const el=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node};const fmt=new Intl.NumberFormat();
function card(label,value){const node=el('div',undefined,'card');node.append(el('div',label,'muted'),el('div',value,'value'));return node}
function renderSummary(s){const root=document.querySelector('#summary');root.replaceChildren(card('Runs',fmt.format(s.runs)),card('Verified',Math.round(s.verifiedRate*100)+'%'),card('Cost / verified',s.costPerVerifiedSuccess==null?'—':'$'+Number(s.costPerVerifiedSuccess).toFixed(4)),card('Tokens',fmt.format(s.totalTokens)),card('Cache reads',fmt.format(s.cachedInputTokens)),card('Tool calls',fmt.format(s.toolCalls)),card('Total cost','$'+Number(s.totalCost).toFixed(4)))}
function renderRuns(rows){const root=document.querySelector('#runs'),table=el('table'),head=el('tr');['Run','Status','Preset','Duration'].forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);const body=el('tbody');for(const row of rows){const tr=el('tr'),button=el('button',row.runId.slice(0,8));button.addEventListener('click',()=>loadDetails(row.runId));const status=el('span',row.verified?'verified':'failed','pill '+(row.verified?'pass':'fail'));tr.append(el('td'));tr.children[0].append(button);tr.append(el('td'));tr.children[1].append(status);tr.append(el('td',row.presetId||row.kind));tr.append(el('td',row.durationMs==null?'—':Math.round(row.durationMs)+' ms'));body.append(tr)}table.append(thead,body);root.replaceChildren(table)}
function renderBenchmarks(rows){const root=document.querySelector('#benchmarks');if(!rows.length)return;const table=el('table'),head=el('tr');['Benchmark','Variants','Quality Δ','Latency Δ','Cost Δ'].forEach(x=>head.append(el('th',x)));const thead=el('thead');thead.append(head);const body=el('tbody');for(const row of rows){const tr=el('tr'),quality=row.verifiedSuccessDelta==null?'—':(row.verifiedSuccessDelta>0?'+':'')+row.verifiedSuccessDelta;tr.append(el('td',row.benchmarkId),el('td',row.variants.length),el('td',quality,row.verifiedSuccessDelta>0?'pass':row.verifiedSuccessDelta<0?'fail':''),el('td',row.latencyDeltaMs==null?'—':Math.round(row.latencyDeltaMs)+' ms'),el('td',row.costDelta==null?'—':'$'+Number(row.costDelta).toFixed(4)));body.append(tr)}table.append(thead,body);root.replaceChildren(table)}
function metric(label,value){const node=el('div',undefined,'metric');node.append(el('div',label,'muted'),el('strong',value));return node}
async function loadDetails(id){try{const d=await api('/api/runs/'+encodeURIComponent(id)),root=document.querySelector('#details');root.replaceChildren(el('div',d.run.runId,'eyebrow'),el('h3',d.task?.objective||d.run.kind),el('p',d.run.output||'No output','muted'));const grid=el('div',undefined,'metric-grid');grid.append(metric('Tokens',fmt.format(d.metrics.totalTokens)),metric('Cost','$'+Number(d.metrics.totalCost).toFixed(4)),metric('First verifier pass',d.metrics.firstPassVerified?'verified':'not verified'),metric('Verifier attempts',d.metrics.repairAttempts),metric('Completion',d.metrics.repair.attribution==='unknown'?'unknown attribution':d.metrics.repair.verifiedAfterRepair?'verified repair':d.metrics.repair.unresolved?'unresolved failure':d.run.verified?'first-pass success':'unverified'),metric('Resolved failures',d.metrics.repair.resolved),metric('Unresolved failures',d.metrics.repair.unresolved),metric('Verified repair',d.metrics.repair.verifiedAfterRepair?'yes':'no'),metric('Requirements',Math.round(d.metrics.requirementCoverage*100)+'%'),metric('Artifacts',Math.round(d.metrics.artifactValidity*100)+'%'),metric('Tool success',Math.round(d.metrics.toolSuccessRate*100)+'%'),metric('Tool latency',Math.round(d.metrics.averageToolLatencyMs)+' ms'),metric('Prefix survival',Math.round(d.metrics.prefixSurvivalRate*100)+'%'),metric('Net cache tokens',fmt.format(d.metrics.netCacheSavings)),metric('Evidence',fmt.format(d.metrics.evidenceItems)),metric('Provenance',Math.round(d.metrics.provenanceCoverage*100)+'%'),metric('Child tokens',fmt.format(d.metrics.childTokens)),metric('Verifier-attempt tokens',fmt.format(d.metrics.repairTokens)),metric('Human correction',Number(d.metrics.humanCorrectionMinutes).toFixed(1)+' min'));root.append(grid,el('h3','Verification'));for(const check of d.verifiers)root.append(el('div',(check.passed?'✓ ':'× ')+check.verifierId+': '+check.message,'event '+(check.passed?'pass':'fail')));root.append(el('h3','Timeline'));for(const event of d.events.slice(-80)){const line=el('div',event.type,'event');line.append(el('small',new Date(event.timestamp).toLocaleString()));root.append(line)}}catch(error){showError(error)}}
function showError(error){document.querySelector('#error').replaceChildren(el('div',error.message||String(error),'error'))}
async function refresh(){try{const [summary,runs,benchmarks]=await Promise.all([api('/api/summary'),api('/api/runs?limit=100'),api('/api/benchmarks')]);renderSummary(summary);renderRuns(runs);renderBenchmarks(benchmarks);document.querySelector('#error').replaceChildren()}catch(error){showError(error)}}refresh();setInterval(refresh,10000);
</script></body></html>`;
}
